[picom-trans] Optimize get_target_window_id()
It was, until now, directly copied from the previous version of
picom-trans.

These modifications make it POSIX compatible (POSIX grep doesnt have -w)
and might improve performance (a few pipes were reduced).

diff --git a/bin/picom-trans b/bin/picom-trans
--- a/bin/picom-trans
+++ b/bin/picom-trans
@@ -160,74 +160,73 @@ parse_args()
 } #}}
 
 
-# NOTE: The code inside the following function has been taken directly from the
-# old version of picom-trans.  Tread cautiously!
 get_target_window_id()
 { #{{
 
-  # Get ID of the target window
-  if test -z "$winidtype"; then
-    treeout=$(xwininfo -children -frame)
-  else
-    test "$winidtype" = "-id" \
-      && ! echo "$winid" | grep -Eiq '^[[:space:]]*(0x[[:xdigit:]]+|[[:digit:]]+)[[:space:]]*$' \
-      && echo "Bad window ID." >&2 \
-      && exit 1
-    treeout=$(xwininfo -children $winidtype "$winid")
+  # Get the output of xwininfo
+  if test -z "$winidtype"
+  then xwininfo_output="$(xwininfo -children -frame)"
+  elif test "$winidtype" = "-name"
+  then xwininfo_output="$(xwininfo -children -name "$winid")"
+  elif test "$winidtype" = "-id"
+  then
+    # First, check if supplied window id is valid
+    if ! echo "$winid" | grep -Eiq '^[[:space:]]*(0x[[:xdigit:]]+|[[:digit:]]+)[[:space:]]*$'
+    then
+      echo "Bad window ID" >&2
+      exit 1
+    fi
+    xwininfo_output="$(xwininfo -children -id "$winid")"
   fi
 
-  wid=$(echo "$treeout" | sed -n 's/^xwininfo:.*: \(0x[[:xdigit:]]*\).*$/\1/p')
-
-  if test -z "$wid"; then
-    echo "Failed to find window." >&2
+  # Extract window id from xwininfo output
+  winid="$(echo "$xwininfo_output" | sed -n 's/^xwininfo:.*: \(0x[[:xdigit:]]*\).*$/\1/p')"
+  if test -z "$winid"
+  then
+    echo "Failed to find window" >&2
     exit 1
   fi
 
   # Make sure it's not root window
-  if echo "$treeout" | grep -Fq "Parent window id: 0x0"; then
-    echo "Cannot set opacity on root window." >&2
+  if echo "$xwininfo_output" | grep -Fq "Parent window id: 0x0"
+  then
+    echo "Cannot set opacity on root window" >&2
     exit 1
   fi
 
-  # If it's already the topmost window
-  if echo "$treeout" | grep -q 'Parent window id: 0x[[:xdigit:]]* (the root window)'; then
-    topmost=$wid
-  else
-    # Get the whole window tree
-    treeout=$(xwininfo -root -tree)
-
-    if test -z "$treeout"; then
-      echo "Failed to get root window tree." >&2
+  # If it's not the topmost window, get the topmost window
+  if ! echo "$xwininfo_output" | grep -q 'Parent window id: 0x[[:xdigit:]]* (the root window)'
+  then
+    window_tree="$(xwininfo -root -tree)"
+    if test -z "$window_tree"
+    then
+      echo "Failed to get root window tree" >&2
       exit 1
     fi
 
-    # Find the line number of the target window in the window tree
-    lineno=$(printf "%s" "$treeout" | grep -nw "^\s*$wid" | head -n1 | cut -d ':' -f 1)
-
-    if test -z "$lineno"; then
-      echo "Failed to find window in window tree." >&2
+    # Find the highest ancestor of the target window
+    winid="$(echo "$window_tree" \
+      | sed "/^\s*$wid/q;s/^     \(0x[[:xdigit:]]*\).*/\1/p" \
+      | tail -n 1)"
+    if test -z "$winid"
+    then
+      echo "Failed to find window in window tree" >&2
       exit 1
     fi
-
-    # Find the highest ancestor of the target window below
-    topmost=$(printf "%s" "$treeout" \
-      | head -n "$lineno" \
-      | sed -n 's/^     \(0x[[:xdigit:]]*\).*/\1/p' \
-      | tail -n 1)
   fi
-
-  if test -z "$topmost"; then
-    echo "Failed to find the highest parent window below root of the selected window." >&2
+  if test -z "$winid"
+  then
+    echo "Failed to find the highest parent window below root of the selected window" >&2
     exit 1
   fi
 
-  echo "$topmost"
+  echo "$winid"
 } #}}
 
 
 get_focused_window_id()
 { #{{
-  id=$(xprop -root -notype -f _NET_ACTIVE_WINDOW 32x '$0' _NET_ACTIVE_WINDOW)
+  id="$(xprop -root -notype -f _NET_ACTIVE_WINDOW 32x '$0' _NET_ACTIVE_WINDOW)"
   echo "${id#_NET_ACTIVE_WINDOW}"
 } #}}
 
@@ -236,8 +235,8 @@ get_current_opacity()
   # Gets current opacity
   # Doesn't ouput anything if opacity isn't set
   cur="$(xprop -id "$winid" -notype -f _NET_WM_WINDOW_OPACITY 32c '$0' _NET_WM_WINDOW_OPACITY)"
-  cur=${cur#_NET_WM_WINDOW_OPACITY}
-  cur=${cur%:*}
+  cur="${cur#_NET_WM_WINDOW_OPACITY}"
+  cur="${cur%:*}"
   echo "$cur"
 } #}}
 
@@ -314,14 +313,16 @@ esac
 
 
 # Check if both xwininfo and xprop are available
-if ! command -v xprop >/dev/null || ! command -v xwininfo >/dev/null; then
-  echo "The command xwininfo or xprop is not available. They might reside in a package named xwininfo, xprop, x11-utils, xorg-xprop, or xorg-xwininfo." >&2
+if ! command -v xprop >/dev/null || ! command -v xwininfo >/dev/null
+then
+  echo "The command xwininfo or xprop is not available. They might reside in a package named xwininfo, xprop, x11-utils, xorg-xprop, or xorg-xwininfo" >&2
   exit 1
 fi
 
 
 # No arguments given. Show help.
-if test $# -eq 0; then
+if test $# -eq 0
+then
   print_usage >&2
   exit 1
 fi
